### ISSUE TITLE
что меняет эта проверка. ее результат никуда не идет!

### ISSUE THREAD

**Issue by paladinbbk** [velenskaya/PHP__Hillel#2]
https://github.com/velenskaya/PHP__Hillel/blob/afa85689ad9e6bcb494099592b7e067337795b4b/array_keys.php#L8

**Comment by velenskaya** [comment]
Я исправила, добавила условие
Не могу понять или чего -то я не вижу, почему выводит NULL (когда вместо массива в функцию в качестве параметра попадает число)

**Comment by paladinbbk** [comment]
ну тогда надо писать 
if (!is_array($arr)) {
return false;
}
