### ISSUE TITLE
эта строка тут ничего не делает 

### ISSUE THREAD

**Issue by paladinbbk** [velenskaya/PHP__Hillel#6]
https://github.com/velenskaya/PHP__Hillel/blob/1e236cdf8db91c547cf9d214576a4bd9f471505e/count.php#L7

**Comment by velenskaya** [comment]
этой строкой я хотела сделать проверку, что функция приняла на вход в качестве параметра  массив, а не какой-то другой тип данных
или  как тогда правильнее писать
function count_my( array $arr)  
или как вы мне в другой функции писали , вот так
if (!is_array($arr)) {
return false;
}
